### PR TITLE
DbFieldCollection

### PR DESCRIPTION
**Pull request by SergerGood**
I tried adding using lazy loading for the DbField collections that uses the DbFieldCache. 
Lazy methods will not be evaluated if no one calls them and will return the calculated value on the next calls.
This way we avoid iterating over the collection every time.

P.S. also removed unused method parameters

### CODE REVIEW

**Comment by mikependon** [comment]
Nice PR mate, thanks for this. There are failing builds. Can you check?

**Comment by SergerGood** [comment]
I run all tests locally. The result is successful

**Comment by mikependon** [comment]
Atleast the Solution Builds are failing the Github home page.

**Comment by SergerGood** [comment]
sorry didn't see it. Yes, I'll see what's going on.

**Comment by SergerGood** [comment]
I skipped a few projects because they weren't included in the RepoDb.All.sln
its OK now

**Comment by mikependon** [comment]
I have reviewed the code early today. Thanks a lot on this PR

**Comment by mikependon** [comment]
I think, by default, we should put this in mind as we improve the library. We are doing the same within our organization, do not even know why I skipped this in RepoDB

**Pull request merged**
