### PR TITLE
Add PropertyInfo.GetHandledValue

### PR DESCRIPTION
**Pull request by davidrot**

### CODE REVIEW

**Comment by mikependon** [comment]
There are 40 tests failing. Would you be able to check? Also, did you see my last comment about the overload method that accepts the argument 'entityType'?

**Comment by davidrot** [comment]
Where can I see the failing tests. RepoDb.UnitTests are working, RepoDb.IntegrationTest is not possible for me because I have no MSSqlServer. Do you have a buildserver?

**Comment by mikependon** [comment]
I think I commented just right after your PR. By that time, the tests are still executing. But upon visiting now, they're all green.

**Comment by davidrot** [comment]
What does that mean?

**Comment by mikependon** [comment]
It means that all the tests were passing. In every project page on Github (ie: Core, SqlServer, MySql, SqLite, PostgreSql and SqlServer.BulkOperations) has their own Unit and Integration Tests at App Veyor. You can click the icon shields to visit the test. Here is the [link](https://ci.appveyor.com/project/mikependon/repodb-qksas/build/tests) for the Core's integration tests.

**Comment by mikependon** [comment]
I can accept your PR now, but will you still do the overload method? I can also do it right after if you wish.

**Comment by davidrot** [comment]
I added already the overload or did I do it wrong? 

```
public static object GetHandledValue(this PropertyInfo propertyInfo, object entity) { ... }
public static object GetHandledValue(this PropertyInfo propertyInfo, Type declaringType, object entity) { ... }
```

**Comment by mikependon** [comment]
Perfect! Thanks!

**Comment by mikependon** [comment]
@davidrot - made a fine review today and added some XML comments. I liked your coding standard. I hope you will contribute more soon.

Btw, I notice you're not a part of the contributors list, I do not why. It might be because you're using different email address (I supposed).

**Comment by davidrot** [comment]
Hi @mikependon,
thanks for the feedback. I think I will contribute in the future. It looks like I'm using RepoDb in a bigger project. 
I've added my commit email address to the github profile, now I'm listed in the contributors list :)

**Pull request merged**
