### PR TITLE
remove some unecessary assignments

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by mikependon** [comment]
Thank you for this. The generated IL is still same right? This is a coding [preference](https://github.com/mikependon/RepoDB/blob/master/RepoDb.Docs/coding-standards.md#usage-of-var-keyword-when-declaring-a-method-level-variables), unless otherwise there is a performance and efficiency impact.

**Comment by mikependon** [comment]
But seems you are correct that the additional assignment is [present](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyDMABGgQMIEDeOB1RhyALAQLIAUAlBVTd8ugAwEAbgEMATmGEAjCAFN0Abi7UAvktpFGAOXads3biNFCxE6XIIBeAiwDKwcQDsA5mwcBXCBEV6aq7MqA=). If I am to accept this, then these area may deviates from the other code we had written all over the place. Thoughts?

```csharp
IL_0001: ldnull
IL_0002: stloc.0
```

**Comment by SimonCropp** [comment]
deviates in what way?

**Comment by mikependon** [comment]
Shallow reason, coding preference / standard?

**Comment by SimonCropp** [comment]
as in u like variables assigned at the top of the function?

**Comment by mikependon** [comment]
No, not that. Only if needed, just right on top of the usage, as you can also see it in the other areas. Maybe our big code base here is not perfect.

**Comment by SimonCropp** [comment]
ok well given your concerns and the conflicts, i will close this one. :)

**Comment by mikependon** [comment]
I am open for change here, I hope you have not closed it yet. You can always persuade me if this is non-var approach is the most ideal one. I can see in this PR, you have done an optimization as well in some other code.

**Comment by SimonCropp** [comment]
i will resubmit based on your preferences

**Pull request closed without merging**
