### PR TITLE
Added some micro optimizations

### PR DESCRIPTION
**Pull request by SergerGood**

### CODE REVIEW

**Comment by jodydonetti** [comment]
I see you've changed a lot of `.Any()` with `.Count()` but isn't it true that `.Count()` have to count all the elements while `.Any()` immediately stop at the first element it finds?
If that is the case, this would be a perf regression, not an optimization.

See: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/AnyAll.cs#L11-L45

**Comment by mikependon** [comment]
Thanks for the clarity here @njy.

**Comment by SergerGood** [comment]
If the .Count() method doesn't know about the collection, it will enumerate over it, which will be an O(n) operation. But the Count property do so in an O(1)

https://www.jetbrains.com/help/resharper/UseCollectionCountProperty.html

**Comment by jodydonetti** [comment]
@SergerGood yes, and that is because - as you can see in the linked source - the `.Any()` method is smart enough to do exactly that 😊

Also, you changed `.Any()` with a `.Count()` method, not property, so your ReSharper link is not related.

**Comment by SergerGood** [comment]
> 
> 
> @SergerGood yes, and that is because - as you can see in the linked source - the `.Any()` method is smart enough to do exactly that 😊

Not always.

> Also, you changed `.Any()` with a `.Count()` method, not property, so your ReSharper link is not related.

Why method? I used property.

**Comment by mikependon** [comment]
The PR only changed from the method `Count()` to `Any()`. But it does changed the `Any()` method to `Count` property, which I supposed much optimal. The `Count` property does contain the value directly and no need to have additional evaluation.

**Comment by jodydonetti** [comment]
@SergerGood and @mikependon my bad: I don't know why but I saw `.Count()` instead of `.Count` and `.Any()` removed in favor of `.Count()`, what the hell?

Probably it's because I'm at the end of a veeery long day at work, sorry for having wasted your time.

**Comment by mikependon** [comment]
You actually answered my question about `Count()` vs `Any()`. And, thanks for asking :)

**Pull request merged**
