### PR TITLE
Benchmarks for the UpdateAll methods

### PR DESCRIPTION
**Pull request by SergerGood**
image

### CODE REVIEW

**Comment by SergerGood** [comment]
It looks unreal

**Comment by mikependon** [comment]
@SergerGood hey man, are the mentioned `BulkUpdateAll` in the results are using the real [BulkUpdate](https://repodb.net/operation/bulkupdate) method of the `RepoDb.SqlServer.BulkOperations` extension library?

**Comment by SergerGood** [comment]
yes, I added link to project in tests

**Comment by mikependon** [comment]
Seems impossible that this bulk execution is allocating much than normal the batch operations. Anyway, you should somehow as well not benchmark the first execution of that (I suppose, that would improve further the `BulkUpdate` with large margin). I made a series of test historically.

**Comment by mikependon** [comment]
@webmasterdevlin - FYI, here is the benchmark I tried to talk to you during our meeting earlier.

**Pull request merged**
