### PR TITLE
Update to MySqlConnector 1.0

### PR DESCRIPTION
**Pull request by bgrainger**
MySqlConnector 1.0 will change the namespace of the library.

This PR shouldn't be merged until MySqlConnector 1.0 (stable) is released, but I'm opening it now to start the conversation.

### CODE REVIEW

**Comment by bgrainger** [comment]
See https://github.com/mysql-net/MySqlConnector/issues/824.

**Comment by bgrainger** [comment]
Updated PR to MySqlConnector 1.0.0 (RTM).

**Comment by mikependon** [comment]
Thank you for this PR.

**Comment by mikependon** [comment]
It usually took me less than 30 seconds to execute the Integration Tests, whereas right now it took me more than 4 mins. 

Change log: https://mysqlconnector.net/overview/version-history/

image

**Comment by mikependon** [comment]
Please ignore this. It has been fixed after restarting the execution many times. It could be my environment bootstrap.

**Pull request merged**
