### PR TITLE
fix convert error for type level with propertyHandler

### LINKED ISSUE #646: Enhancement: can't custom db string -> enum property by IPropertyHandler<string, TEnum>
I define `DbValueAttribute` to assign mapping value in database, ex:
```
public enum SpeedEnum {
   [DbValue("(FX)")] High,     // database field value is (FX)
   [DbValue("(FY)")] Middle,  // database field value is (FY)
   [DbValue("(FZ)")] Low       // database field value is (FZ)
}
```
have generic PropertyHandler
```
public class DbValueEnumPropertyHandler<TEnum>: IPropertyHandler<string, TEnum?> {
   public TEnum? Get(string input, ClassProperty property) { .... }
   public TDbValue Get(TEnum? input, ClassProperty property) { .... }
}
```
unittest:
```
Assert.Equal(Connection.ExecuteQuery<string>($"select @a", new { a = SpeedEnum.Middle }).First(), "(FY)");    // success
Assert.Equal(Connection.ExecuteQuery<SpeedEnum>($"select N'(FY)'").First(), SpeedEnum.Middle);  // fail
```
exception is
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Compiler.DataReader.IsDbNull.TrueExpression: Failed to convert the value expression for property handler ''. Context :: TargetType: SpeedEnum
  Source=<無法評估例外狀況來源>
  StackTrace: 
<無法評估例外狀況堆疊追蹤>

  此例外狀況原先在此呼叫堆疊擲回: 
    [外部程式碼]

內部例外狀況 1:
InvalidOperationException: 類型 'SpeedEnum' 與 'System.String' 間未定義強制型轉運算子。
```
seem `GetClassPropertyParameterInfoIsDbNullFalseValueExpression` in `RepoDb.Core\RepoDb\Reflection\Compiler\Compiler.cs`
call `ConvertExpressionToEnumExpression` when from string to enum
bypass PropertyHandler

hope you can help,
thank you.

### PR DESCRIPTION
**Pull request by fredliex**
fix #646  .

Please let me know if there is anything not considered.
I will try to fix it again.

thank

### CODE REVIEW

**Comment by mikependon** [comment]
Hi, can you provide more context on this PR? Let me understand your problem and the solution you introduced on the 3 files. Just a high-level information of the problem and solution would help a lot. Though, I will look at this PR soon.

Looking forward to hearing from you.

**Comment by fredliex** [comment]
I want to use PropertyHandler to map Enum to any database type, which may be varchar, int, float, decimal... etc. of specific values.

If Enum is in the model, the original operation is expected.
```csharp
public class SomeModel {
   public SomeEnum Prop1 { get; set; }  // mapping to decimal 100
   ......
}
connection.ExecuteQuery<SomeModel>("select convert(decimal, 100) as Prop1");
```

However, if you directly correspond to the type, there will be a transformation error. The reason is that the processing of the PropertyHandler will be skipped in some cases.
```csharp
connection.ExecuteQuery<SomeEnum>("select convert(decimal, 100)");
```

The main correction of this PR is that when the type corresponds, the conversion type can be determined according to the type of the PropertyHandler to avoid conversion errors.

in `GetClassPropertyParameterInfoIsDbNullTrueValueExpression`
mainly changed is to obtain the propertyHandler based on the classProperty or entity type. If the propertyHandler exists, the target type of convertion is determined based on the propertyHandler.

in `GetPlainTypeToDbParametersCompiledFunction`
mainly changed is to determine if a propertyHandler exists, then the value of `DbParameter.DbType` is determined according to the propertyHandler.

**Comment by mikependon** [comment]
This is just for me ~ I saw some `out/ref` in the code. Though, it was not a part of our coding standards yet, but I am trying to remove it from the way we do things in RepoDB. We have few of this historically, which I already started refactoring.

This is to avoid a back-door referencing of the variables, in which could add more complexities on the code and the way we do the debugging. If you have a chance, maybe try to refactor the code a little to remove the `out/ref` keywords.

Also, please give me a little time to review this one, maybe after the Christmas Holiday. :) Thanks for this PR.

**Comment by fredliex** [comment]
I have considered the suitability of out parameter, but in the end, in order to avoid repeated get of the Set return type of the PropertyHandler, and to avoid a large amount of code modification, the out parameter is used first after the choice.

Or can it return ValueTuple?
If ValueTuple can be used, I can use ValueTuple instead of out parameter.

**Comment by mikependon** [comment]
This is the reason these objects [class](https://github.com/mikependon/RepoDB/blob/52723590c6aa768d2fd0a56f5b07f695b7128702/RepoDb.Core/RepoDb/Reflection/Compiler/Compiler.cs#L27), [MemberBinding](https://github.com/mikependon/RepoDB/blob/52723590c6aa768d2fd0a56f5b07f695b7128702/RepoDb.Core/RepoDb/Reflection/Compiler/Compiler.cs#L110) class and [FieldDirection](https://github.com/mikependon/RepoDB/blob/52723590c6aa768d2fd0a56f5b07f695b7128702/RepoDb.Core/RepoDb/Reflection/Compiler/Compiler.cs#L100) exists.

Would you be able to place this one on a branch?

**Comment by mikependon** [comment]
Fat finger, I am using my phone and accidentally close it. ~Reopening~

**Comment by fredliex** [comment]
What if it looks like this?

```csharp
internal static Expression ConvertExpressionToPropertyHandlerSetExpression(Expression expression,
    ClassProperty classProperty,
    Type targetType)
    => ConvertExpressionToPropertyHandlerSetExpressionCore(expression, classProperty, targetType).expression;

internal static (Expression expression, Type handlerSetType) ConvertExpressionToPropertyHandlerSetExpressionCore(Expression expression,
    ClassProperty classProperty,
    Type targetType)
{ 
    return ......
}
```

This can omit the definition of temporary classes.

**Comment by mikependon** [comment]
It is ok to use Tuple, but I would say, just leave it for now and let me do the thorough review after the holidays, so I can provide more better insights. What I can say, the method name itself should do what it is meant to do. Definitely, naming should be Tuple and not Expression then :)

Btw, can you create a branch for this? Also, is this something you are needing very soon?

**Comment by fredliex** [comment]
Sorry, I don't quite understand what you mean.
Does "create branch" mean in my fork repository?

There is no time pressure for nuget push.
But I hope to merge to master as soon as possible, so that my subsequent tests can continue.

thank

**Comment by mikependon** [comment]
@fredliex - anyway, you can just ignore my request as I can see your branch `Fix/Enum_PropertyHandler` under your own account, I can always work there.

Just in case you want to fix something in the near future, you can now create a branch directly to the main line as I just made you a collaborator.

**Comment by fredliex** [comment]
I just tried to create a branch in your repository, but I still don't seem to have permission.

I have changed the out parameter to return tuple in `Fix/Enum_PropertyHandler` branch on `fredliex/RepoDB` repository.

thank.

**Comment by fredliex** [comment]
Sorry, I didn't notice the collaborationator invitation letter.
I will try to branch here later.

**Comment by fredliex** [comment]
ok, the branch `fix_Enum_PropertyHandler` has been established here.

Use the method of returning Tuple.

thank

**Comment by mikependon** [comment]
@fredliex - after the review, I would say that this is a very nice PR. Many thanks for this! I am currently running all our Integration Tests (cross data providers), hopeful to have all of them green. Cross fingers!

**Comment by mikependon** [comment]
[Thanks](https://twitter.com/mike_pendon/status/1343227738161881088) again for pushing this @fredliex !

**Pull request merged**
